config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  #ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #ユーザCRUD機能
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/users/account', to: 'users#show_account'
  get '/users/edit', to: 'users#edit_account'
  patch '/users/edit', to: 'users#update_account'

  get '/users/profile', to: 'users#edit_profile'
  patch '/users/profile', to: 'users#update_profile'

  #ルームCRUD機能
  resources :rooms, except: [:show, :destroy, :edit] do
  #検索機能
    collection do
      get 'search'
    end
  end

  #予約機能
  resources :bookings, only: [:index, :show, :new, :create] do
    post :confirm, action: :confirm_new, on: :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  require 'bigdecimal'
  require "date"

  belongs_to :user
  belongs_to :room

  validates :number_of_users, presence: true, numericality: { in: 1..999 }
  validates :start_date, presence: true
  validates :termination_date, presence: true

  validate  :validate_overdue_now
  validate  :validate_overdue_start_date

  TAX_RATE = "1.1"
  attr_accessor :days_of_use

  def sum_up_total_charge
    self.days_of_use = (self.termination_date - self.start_date).to_i
    self.room = Room.find(room_id)
    self.total_charge = (BigDecimal(self.room.charge.to_s) * BigDecimal(self.days_of_use.to_s) * BigDecimal(self.number_of_users.to_s) * BigDecimal(TAX_RATE)).ceil
  end

  def start_date_formated
    start_date.strftime("%Y年 %m月 %d日")
  end

  def termination_date_formated
    termination_date.strftime("%Y年 %m月 %d日")
  end

  private

    def validate_overdue_now
      return if start_date.nil?
      errors.add(:start_date, "が現在日付の過去です") if start_date.strftime("%x") < DateTime.current.strftime("%x")
    end

    def validate_overdue_start_date
      return if start_date.nil?
      return if termination_date.nil?
      errors.add(:termination_date, "が開始日の同日か過去です") if termination_date <= start_date
    end

end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :bookings

  validates :name, length: { in: 3..50 }, presence: true
  validates :introduction, length: { in: 5..300 }, presence: true
  validates :charge, presence: true, numericality: { in: 1..100 }
  validates :address,length: { in: 3..100 }, presence: true
  validates :image, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_one_attached :image
  has_many :rooms
  has_many :bookings

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :password, length: { in: 5..20 }, on: [:create, :update_account]
  validates :password, confirmation: true, on: [:create, :update_account]
  validates :password_confirmation, presence: true, on: [:create, :update_account]
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required
  before_action :set_search

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end

  def set_search
    @q = Room.ransack(params[:q])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
    @room = Room.find(params[:room_id])
    @booking.room_id = params[:room_id]
  end

  def confirm_new
    @booking = current_user.bookings.new(booking_params)
    if @booking.valid?
      @booking.sum_up_total_charge()
    else
      @room = Room.find(params[:room_id])
      render :new
    end
  end

  def create
    @booking = current_user.bookings.build(booking_params)

    if params[:back].present?
      @room = Room.find(@booking.room_id)
      render :new
      return
    end

    if @booking.save
      flash[:notice] = "ルームを予約しました"
      redirect_to booking_path(@booking)
    else
      @room = Room.find(@booking.room_id)
      render :new
    end
  end

  def show
    @booking= Booking.find(params[:id])
  end

  def destroy
    @booking= current_user.bookings.find(params[:id])
    @booking.destroy
    flash[:notice] = "ルームを削除しました"
    redirect_to :bookings
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :termination_date, :number_of_users, :room_id, :total_charge)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :login_required

  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  skip_before_action :login_required, only:[:search, :index]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.new(params.require(:room).permit(:name, :introduction, :charge, :address, :image,))
    if @room.save
      flash[:notice] = "ルームを新規登録しました"
      redirect_to new_booking_path(:room_id => @room.id)
    else
      render "new"
    end
  end

  def search
    @q = Room.ransack(params[:q])
    @rooms = @q.result
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'ログインしました'
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 skip_before_action :login_required,  only:[:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      flash[:notice] = "アカウントを新規登録しました"
      redirect_to root_url
    else
      render "new"
    end
  end

  def show_account
    @user = current_user
  end

  def edit_account
    @user = current_user
  end

  def update_account
    @user = current_user
    if @user.update(params.require(:user).permit(:email, :password, :password_confirmation))
      flash[:notice] = "アカウント情報を更新しました"
      redirect_to users_account_path
    else
      render :edit_account
    end
  end

  def edit_profile
    @user = current_user
  end

  def update_profile
    @user = User.find(current_user.id)
    if @user.update(params.require(:user).permit(:name, :introduction, :image))
      flash[:notice] = "プロフィール情報を更新しました"
      redirect_to users_profile_path
    else
      render :edit_profile
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/confirm_new.html.erb
    <%= render "shared/header" %>

    <%= render "shared/error", obj: @booking %>

    <% if flash.notice %>
      <p class="notice"><%= flash.notice %></p>
    <% end %>

    <div class="container reservations-new">
      <div class="row">
        <div class="col-6 offset-3">
          <div class="reservations-new-nav">

            <h4 class="reservations-new-check-content">予約内容確認</h4>
            <h5 >¥ <%= @booking.room.charge.to_i() %>  / 日</h5>

              <div class="reservations-new-date-select">
                <%= form_for @booking do |f| %>

                  <%= f.label :start_date ,"開始日" %>
                  <%= f.date_field :start_date, class: "form-control mb-4", readonly: "" %>

                  <%= f.label :termination_date ,"終了日" %>
                  <%= f.date_field :termination_date, class: "form-control mb-4", readonly: "" %>

                  <h6 class="reservations-new-check-content">使用日数 :<%= @booking.days_of_use %> 日</h6>
                  <h6 class="reservations-new-check-content">人数     :<%= @booking.number_of_users %> 人</h6>

                  <h6 class="reservations-new-check-content">合計金額:<%= @booking.total_charge.to_i() %> 円</h6>

                  <%= f.hidden_field :total_charge %>
                  <%= f.hidden_field :number_of_users %>
                  <%= f.hidden_field :room_id %>
                  <%= f.hidden_field :user_id %>

                  <p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>

                  <%= f.submit "予約を確定", class: ["form-control","btn","btn-primary", "my-3"] %>
                  <%= f.submit "戻る", name: "back", class: ["form-control","btn","btn-secondary", "my-3"] %>

                <% end %>
              </div>

           </div>
        </div>
      </div>
    </div>

    <%= render "shared/footer" %>

app/views/bookings/index.html.erb
    <%= render "shared/header" %>

    <% if flash.notice %>
      <p class="notice"><%= flash.notice %></p>
    <% end %>

    <div class="container-fiuld reservations">
      <h4 class="pb-4">予約済みルーム一覧</h4>

      <table>
        <thead>
          <tr align="center">
            <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>ルーム紹介</th>
            <th>合計料金</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>予約確定日時</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %>
            <tr align="center">
              <td>
                <% if booking.room.image.attached? %>
                  <%= link_to image_tag(booking.room.image, class: "reservations-image"), new_booking_path(:booking_id => booking.id) %>
                <% else %>
                  <%= link_to image_tag("default_icon.jpeg", class: "reservations-image"), new_booking_path(:booking_id => booking.id) %>
                <% end %>
              <td class="posts-name"><%= link_to booking.room.name, new_booking_path(:booking_id => booking.id) %></td>
              <td class="posts-content"><%= booking.room.introduction%></td>
              <td>¥ <%= booking.total_charge.to_i() %> </td>
              <td><%= booking.start_date.to_s(:datetime_jp) %> </td>
              <td><%= booking.termination_date.to_s(:datetime_jp) %> </td>
              <td><%= booking.created_at.to_s(:datetime_jp) %> </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <%= render "shared/footer" %>

app/views/bookings/new.html.erb
    <%= render "shared/header" %>

    <%= render "shared/error", obj: @booking %>

    <% if flash.notice %>
      <p class="notice"><%= flash.notice %></p>
    <% end %>

    <div class="container-fluid room-show">
      <div class="row">

        <div class="col-md-8">

          <% if @room.image.attached? %>
            <%= image_tag @room.image, class: "room-show-image" %>
          <% else %>
            <%= image_tag "default_icon.jpeg", class: "room-show-image" %>
          <% end %>

          <div class="room-show-detile">

            <div class="room-show-detile-icon">
              <% if @room.user.image.attached? %>
                <%= image_tag @room.user.image, class: "host-icon" %>
              <% else %>
                <%= image_tag "default_icon.jpeg", class: "host-icon" %>
              <% end %>
            </div>

            <div class="room-show-profile">
              <p class="room-show-profile-name">
                <%= @room.user.name %>
              </p>
              <p class="room-show-profile-address">
                <%= @room.address %>
              </p>
            </div>

          </div>

          <p class="room-show-detile-content">
            <%= @room.introduction %>
          </p>

        </div>

        <div class="col-md-4">
          <div class="room-show-nav">
            <h5 class="price-icon">¥ <%= @room.charge.to_i() %> / 日</h5>

            <div class="room-show-date-select">

              <%= form_for @booking, url: confirm_new_booking_path(room_id: @room.id) do |f| %>

              <%= f.label :start_date ,"開始日" %>
              <%= f.date_field :start_date, class: "form-control mb-4" %>

              <%= f.label :termination_date ,"終了日" %>
              <%= f.date_field :termination_date, class: "form-control mb-4" %>

              <%= f.label :number_of_users ,"人数" %>
              <%= f.number_field :number_of_users, min: 1, max: 9999, class: "form-control mb-4" %>

              <%= f.hidden_field :room_id %>

              <%= f.submit "予約する", class: ["form-control","btn","btn-primary"] %>
              <% end %>
              </div>

          </div>
        </div>

      </div>
    </div>

    <%= render "shared/footer" %>

app/views/bookings/show.html.erb
    <%= render "shared/header" %>

    <%= render "shared/error", obj: @booking %>

    <% if flash.notice %>
      <p class="notice"><%= flash.notice %></p>
    <% end %>

    <div class="container-fiuld user">
      <div class="row">
        <div class="col-md-12 user-view">
           <div class="user-view-box">

              <div class="update-content">
                <div class="row">
                  <label class="col-md-3"><strong>予約した部屋</strong></label>
                  <div class="col-md-9">
                    <%= link_to @booking.room.name, new_booking_path(room_id: @booking.room_id) %>
                  </div>
                </div>
              </div>

              <div class="update-content">
                <div class="row">
                  <label class="col-md-3"><strong>開始日</strong></label>
                  <div class="col-md-9"><%= @booking.start_date_formated() %></div>
                </div>
              </div>

              <div class="update-content">
                <div class="row">
                  <label class="col-md-3"><strong>終了日</strong></label>
                  <div class="col-md-9"><%= @booking.termination_date_formated() %></div>
                </div>
              </div>

              <div class="update-content">
                <div class="row">
                  <label class="col-md-3"><strong>価格</strong></label>
                  <div class="col-md-9"><%= @booking.total_charge.to_i() %> 円</div>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>

      <%= render "shared/footer" %>

app/views/home/index.html.erb
  <%= render "shared/header" %>

  <% if flash.notice %>
    <p class="notice"><%= flash.notice %></p>
  <% end %>

  <main class="jumbotron jumbotron-fluid top-cover">
    <div class="container top-content">
      <div class="row col-lg-6">
        <div class="form-frame">
          <div class="form-area">
            <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
            <%= search_form_for @q, url: search_rooms_path do |f| %>
              <label>エリア</label>
              <div class="col-sm3 card-text my-3">
                <%= f.search_field :address_cont, class: ["form-control", "mb-4", "search-input"], placeholder: '東京'  %>
              </div>
              <div class="col-sm3 card-text my-3">
                <%= f.submit '探す', class: ["btn", "btn-primary", "form-control", "search-btn"] %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </main>

  <aside class="container">
    <div class="m-5">
      <h1 class="section-title">おすすめのエリア</h1>
      <div class="row justify-content-center">

        <div class="card col-sm-2 mx-2 p-0">
          <%= link_to image_tag("img_tokyo.jpeg", class: "card-img"), search_rooms_path(q: {address_cont: "東京"}), class: "card-img" %>
          <div class="card-img-overlay">
            <p class="text-white">東京</p>
          </div>
        </div>

        <div class="card col-sm-2 mx-2 p-0">
          <%= link_to image_tag("img_osaka.jpeg", class: "card-img"), search_rooms_path(q: {address_cont: "大阪"}), class: "card-img" %>
          <div class="card-img-overlay">
            <p class="text-white">大阪</p>
          </div>
        </div>

        <div class="card col-sm-2 mx-2 p-0">
          <%= link_to image_tag("img_kyoto.jpeg", class: "card-img"), search_rooms_path(q: {address_cont: "京都"}), class: "card-img" %>
          <div class="card-img-overlay">
            <p class="text-white">京都</p>
          </div>
        </div>

        <div class="card col-sm-2 mx-2 p-0">
          <%= link_to image_tag("img_sapporo.jpeg", class: "card-img"), search_rooms_path(q: {address_cont: "札幌"}), class: "card-img" %>
          <div class="card-img-overlay">
            <p class="text-white">札幌</p>
          </div>
        </div>
      </div>
    </div>
  </aside>

  <%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoomsharingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/rooms/index.html.erb
    <%= render "shared/header" %>

    <% if flash.notice %>
      <p class="notice"><%= flash.notice %></p>
    <% end %>

    <div class="container-fiuld room-posts">
      <h4 class="pb-4">登録済みルーム一覧</h4>

      <table>
        <thead>
          <tr align="center">
            <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>ルーム紹介</th>
            <th>料金</th>
            <th>作成日</th>
          </tr>
        </thead>
        <tbody>
          <% @rooms.each do |room| %>
            <tr>
              <td>
                <% if room.image.attached? %>
                  <%= link_to image_tag(room.image, class: "room-posts-image"), new_booking_path(:room_id => room.id) %>
                <% else %>
                  <%= link_to image_tag("default_icon.jpeg", class: "room-posts-image"), new_booking_path(:room_id => room.id) %>
                <% end %>
              <td class="posts-name"><%= link_to room.name, new_booking_path(:room_id => room.id) %></td>
              <td class="posts-content"><%= room.introduction%></td>
              <td class="price-icon">¥ <%= room.charge.to_i() %> </td>
              <td><%= room.created_at.to_s(:datetime_jp) %> </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <%= render "shared/footer" %>

app/views/rooms/new.html.erb
    <%= render "shared/header" %>

    <%= render "shared/error", obj: @room %>

    <% if flash.notice %>
      <p class="notice"><%= flash.notice %></p>
    <% end %>

    <div class="container-fiuld">
      <div class="row">

        <div class="col-lg-2 nav-pills user-nav">
          <div class="nav-item">
            <%= link_to "基本情報", new_room_path, class: "nav-link" %>
          </div>
        </div>

        <div class="col-lg-10 user-view">

          <% if flash.notice %>
            <p class="notice"><%= flash.notice %></p>
          <% end %>

          <div class="user-view-box">

            <div class="row update-content">
              <h5 class="room-show-check-content">ルーム情報登録</h5>
            </div>

          <%= form_for @room do |f| %>

              <div class="row update-content align-items-center">
                <div class="col-sm-2 ms-3 px-0"><strong>ルーム名</strong></div><div class="required col-sm-1">必須</div>
                <div class="col-sm-5" ><%= f.text_field :name, class: "form-control", placeholder: "ルーム名を入力" %></div>
              </div>

              <div class="row update-content align-items-center">
                <div class="col-sm-2 ms-3 px-0"><strong>ルーム紹介</strong></div><div class="required col-sm-1">必須</div>
                <div class="col-sm-5"><%= f.text_area :introduction, class: "form-control", placeholder: "ルーム説明を入力"  %></div>
              </div>

              <div class="row update-content align-items-center">
                <div class="col-sm-2 ms-3 px-0"><strong>料金</strong></div><div class="required col-sm-1">必須</div>
                <div class="col-sm-5"><%= f.text_field :charge, class: "form-control", placeholder: "１日あたりの料金を入力"  %></div>
              </div>

              <div class="row update-content align-items-center">
                <div class="col-sm-2 ms-3 px-0"><strong>住所</strong></div><div class="required col-sm-1">必須</div>
                <div class="col-sm-5"><%= f.text_field :address, class: "form-control", placeholder: "住所を入力" %></div>
              </div>

              <div class="row update-content align-items-center">
                <div class="col-sm-2 ms-3 px-0"><strong>ルーム画像</strong></div><div class="required col-sm-1">必須</div>
                <div class="col-sm-5" ><%= f.file_field :image, class: "form-control", placeholder: "ルーム名を入力" %></div>
              </div>

            <div class="row update-content align-items-center">
              <%= f.submit "登録", class: ["col-md-2 btn btn-primary mx-3"] %>
            </div>
          <% end %>

        </div>

      </div>
    </div>

    <%= render "shared/footer" %>

app/views/shared/_error.html.erb
    <% if obj.errors.any? %>
      <% obj.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></p>
        </ul>
      <% end %>
    <% end %>

app/views/shared/_footer.html.erb
  <footer>
    <address>© 2020 POTEPAN.INC.</address>
  </footer>

app/views/shared/_header.html.erb
  <header>
    <nav class="header-nav">

      <div class="header-left-nav">
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'logo.png' %>
        <% end %>
        <div class="form d-flex align-items-center">
          <%= search_form_for @q, url: search_rooms_path do |f| %>
          <div class="aria-search-box">
            <%= f.search_field :address_cont, placeholder: 'エリア'%>
          </div>
          <div class="word-search-box">
          <%= f.search_field :introduction_cont, placeholder: 'キーワード' %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="header-right-nav d-flex align-items-center">
        <% if current_user %>
          <p class="text-white pt-2 pe-3"><%= current_user.name %></p>
          <div class="nav-item dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" id="dropdpwnMenuButton"
               aria-haspopup="true" aria-expanded="false">
              <% if current_user.image.attached? %>
                <%= image_tag current_user.image, class: "nav-host-icon" %>
              <% else %>
                <%= image_tag "default_icon.jpeg", class: "nav-host-icon" %>
              <% end %>
              </a>
            <div class="dropdown-menu" aria-labelledby="dropdpwnMenuButton">
              <div class="dropdown-item"><%= link_to "ルーム登録", new_room_path %></div>
              <div class="dropdown-item"><%= link_to "登録済みルーム一覧", rooms_path %></div>
              <div class="dropdown-item"><%= link_to "予約済みルーム一覧", bookings_path %></div>
              <div class="dropdown-item"><%= link_to "設定", users_account_path %></div>
              <div class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete %></div>
            </div>
          </div>
        <% else %>
          <div class="nav-acoount-form d-flex align-items-center">
            <%= link_to 'ログイン', login_path, class: ["navbar-item", "btn", "btn-primary", "text-white", "m-1"] %>
            <%= link_to '新規登録', register_path, class: ["navbar-item", "btn", "btn-primary", "text-white", "m-1"] %>
          </div>
        <% end %>
      </div>
    </nav>
  </header>

app/views/users/edit_account.html.erb
    <%= render "shared/header" %>
    <%= render "shared/error", obj: @user %>

    <div class="user-view-box">

      <div class="user-edit-frame">
        <h2 class="mb-3">アカウント編集</h2>

        <%= form_for @user, url: users_edit_path do |f| %>

            <div class="form-group">
              <%= f.label :email ,"メールアドレス" %>
              <%= f.text_field :email, class: "form-control", placeholder: "メールアドレスを入力してください" %>
            </div>
            <div class="form-group">
              <%= f.label :password ,"変更後パスワード（変更する場合のみ入力）" %>
              <%= f.text_field :password, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation ,"パスワード確認用（変更する場合のみ入力）" %>
              <%= f.text_field :password_confirmation, class: "form-control" %>
            </div>

          <div class="form-group">
            <%= f.submit "更新", class: ["form-control", "btn-primary", "my-4"] %>
          </div>

          <div class="form-group">
            <%= link_to "戻る", users_account_path, class: "form-control" %>
          </div>

        <% end %>

      </div>
    </div>

    <%= render "shared/footer" %>

app/views/users/new.html.erb
    <%= render "shared/header" %>

    <%= render "shared/error", obj: @user %>

    <% if flash.notice %>
      <p class="notice"><%= flash.notice %></p>
    <% end %>

    <section class="row justify-content-center my-sm-5">
      <div class="card text-center ms-5 px-2 py-4" style="max-width: 38rem;">
        <p class="my-4">新しいアカウントを作成</p>

        <%= form_for @user, url: register_path(@user) do |f| %>

        <div class="row justify-content-center align-items-center">
          <div class="col-sm-1 required">必須</div>
          <div class ="col-sm-6 px-sm-0">
            <%= f.text_field :name, class: "form-control", placeholder: "ユーザー名" %>
          </div>
        </div>

        <div class="row justify-content-center align-items-center">
          <div class="col-sm-1 required">必須</div>
          <div class="col-sm-6 px-sm-0">
            <%= f.text_field :email, class: "form-control", placeholder: "メールアドレス" %>
         </div>
        </div>

        <div class="row justify-content-center align-items-center">
          <div class="col-sm-1 required">必須</div>
          <div class="col-sm-6 px-sm-0">
            <%= f.text_field :password, class: "form-control",  placeholder: "パスワード" %>
          </div>
        </div>

        <div class="row justify-content-center align-items-center">
          <div class="col-sm-1 required">必須</div>
          <div class="col-sm-6 px-sm-0">
            <%= f.text_field :password_confirmation, class: "form-control", placeholder: "パスワード（確認）" %>
          </div>
        </div>

        <div class="row justify-content-center align-items-center">
          <div class="col-sm-8">
            <%= f.submit "新しいアカウントを作成", class: ["form-control","btn","btn-primary"] %>
          </div>
        </div>

        <div class="row justify-content-center align-items-center">
          <div class="col-sm-8">
            <%= link_to "既にアカウントをお持ちの方はログイン", login_path, class: ["btn" "btn-link"] %>
          </div>
        </div>

        <% end %>

      </div>
    </section>

    <%= render "shared/footer" %>

app/views/users/show_account.html.erb
    <%= render "shared/header" %>
    <%= render "shared/error", obj: @user %>

    <div class="container-fiuld">
      <div class="row">

        <div class="col-lg-2 nav-pills user-nav">
          <div class="nav-item">
            <%= link_to "アカウント", users_account_path, class:  ["nav-link","active"]  %>
          </div>
          <div class="nav-item">
            <%= link_to "プロフィール", users_profile_path, class: "nav-link" %>
          </div>
        </div>

        <div class="col-lg-10 user-view">

          <% if flash.notice %>
            <p class="notice"><%= flash.notice %></p>
          <% end %>

          <div class="user-view-box">

            <div class="row update-content">
              <h5>アカウント</h5>
            </div>

              <div class="row update-content">
                <label class="col-md-3" for="email"><strong>メールアドレス</strong></label>
                <div class="col-md-9"><%= @user.email %></div>
              </div>

              <div class="row update-content">
                <label class="col-md-3" for="password"><strong>パスワード</strong></label>
                <div class="col-md-9"><%= @user.password %></div>
              </div>

            <div class="row update-content">
              <%= link_to "編集する", users_edit_path, class: ["col-md-2", "btn", "btn-primary", "mx-3", "text-white"] %>
            </div>

        </div>

      </div>
    </div>

    <%= render "shared/footer" %>